development: &default
  adapter: postgresql
  database: fantasma_development
  encoding: utf8
  min_messages: warning
  host: localhost
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: fantasma_test
